version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout

      - run:
          name: Install unzip
          command: |
            sudo apt-get update
            sudo apt-get -y install unzip

      - run:
          name: Install terraform
          command: |
            wget https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
            unzip terraform_0.12.28_linux_amd64.zip
            sudo chmod +rx terraform
            sudo mv terraform /usr/local/bin/terraform
            terraform init

      - run:
          name: Plan
          command: terraform plan

workflows:
  version: 2
  setup:
    jobs:
      - build
